// ============================================================================
// Default CSS computed style values — used to diff against so we only
// serialize properties that differ from browser defaults.
// Ported from Figma's H2D capture script.
// ============================================================================

export const DEFAULT_STYLES: Record<string, string> = {
  alignContent: 'normal',
  alignItems: 'normal',
  alignSelf: 'auto',
  aspectRatio: 'auto',
  backdropFilter: 'none',
  backgroundAttachment: 'scroll',
  backgroundBlendMode: 'normal',
  backgroundClip: 'border-box',
  backgroundColor: 'rgba(0, 0, 0, 0)',
  backgroundImage: 'none',
  backgroundOrigin: 'padding-box',
  backgroundPositionX: '0%',
  backgroundPositionY: '0%',
  backgroundRepeat: 'repeat',
  backgroundSize: 'auto',
  borderBottomColor: 'rgb(0, 0, 0)',
  borderBottomLeftRadius: '0px',
  borderBottomRightRadius: '0px',
  borderBottomStyle: 'none',
  borderBottomWidth: '0px',
  borderCollapse: 'separate',
  borderImageOutset: '0',
  borderImageRepeat: 'stretch',
  borderImageSlice: '100%',
  borderImageSource: 'none',
  borderImageWidth: '1',
  borderLeftColor: 'rgb(0, 0, 0)',
  borderLeftStyle: 'none',
  borderLeftWidth: '0px',
  borderRightColor: 'rgb(0, 0, 0)',
  borderRightStyle: 'none',
  borderRightWidth: '0px',
  borderSpacing: '0px',
  borderTopColor: 'rgb(0, 0, 0)',
  borderTopLeftRadius: '0px',
  borderTopRightRadius: '0px',
  borderTopStyle: 'none',
  borderTopWidth: '0px',
  bottom: 'auto',
  boxShadow: 'none',
  boxSizing: 'content-box',
  clip: 'auto',
  clipPath: 'none',
  clipRule: 'nonzero',
  color: 'rgb(0, 0, 0)',
  colorScheme: 'normal',
  columnCount: 'auto',
  columnFill: 'balance',
  columnGap: 'normal',
  columnRuleColor: 'rgb(0, 0, 0)',
  columnRuleStyle: 'none',
  columnRuleWidth: '0px',
  columnSpan: 'none',
  columnWidth: 'auto',
  contain: 'none',
  containerType: 'normal',
  content: 'normal',
  contentVisibility: 'visible',
  display: '',
  filter: 'none',
  flexBasis: 'auto',
  flexDirection: 'row',
  flexGrow: '0',
  flexShrink: '1',
  flexWrap: 'nowrap',
  fontFamily: 'Times',
  fontFeatureSettings: 'normal',
  fontKerning: 'auto',
  fontOpticalSizing: 'auto',
  fontPalette: 'normal',
  fontSize: '16px',
  fontSizeAdjust: 'none',
  fontStretch: '100%',
  fontStyle: 'normal',
  fontWeight: '400',
  gridAutoColumns: 'auto',
  gridAutoFlow: 'row',
  gridAutoRows: 'auto',
  gridColumnEnd: 'auto',
  gridColumnStart: 'auto',
  gridRowEnd: 'auto',
  gridRowStart: 'auto',
  gridTemplateAreas: 'none',
  gridTemplateColumns: 'none',
  gridTemplateRows: 'none',
  height: 'auto',
  isolation: 'auto',
  justifyContent: 'normal',
  justifyItems: 'normal',
  justifySelf: 'auto',
  left: 'auto',
  letterSpacing: 'normal',
  lineBreak: 'auto',
  lineHeight: 'normal',
  listStyleImage: 'none',
  listStylePosition: 'outside',
  listStyleType: 'disc',
  marginBottom: '0px',
  marginLeft: '0px',
  marginRight: '0px',
  marginTop: '0px',
  maxHeight: 'none',
  maxWidth: 'none',
  minHeight: '0px',
  minWidth: '0px',
  mixBlendMode: 'normal',
  objectFit: 'fill',
  opacity: '1',
  outlineColor: 'rgb(0, 0, 0)',
  outlineOffset: '0px',
  outlineStyle: 'none',
  outlineWidth: '0px',
  overflow: 'visible',
  overflowX: 'visible',
  overflowY: 'visible',
  paddingBottom: '0px',
  paddingLeft: '0px',
  paddingRight: '0px',
  paddingTop: '0px',
  position: 'static',
  right: 'auto',
  rotate: 'none',
  rowGap: 'normal',
  scale: 'none',
  strokeDasharray: 'none',
  strokeDashoffset: '0px',
  strokeLinecap: 'butt',
  strokeLinejoin: 'miter',
  strokeMiterlimit: '4',
  strokeOpacity: '1',
  strokeWidth: '1px',
  textAlign: 'start',
  textDecorationColor: 'rgb(0, 0, 0)',
  textDecorationLine: 'none',
  textDecorationStyle: 'solid',
  textIndent: '0px',
  textShadow: 'none',
  textTransform: 'none',
  top: 'auto',
  transform: 'none',
  transformOrigin: '50% 50%',
  translate: 'none',
  transitionProperty: 'all',
  verticalAlign: 'baseline',
  visibility: 'visible',
  whiteSpace: 'normal',
  width: 'auto',
  willChange: 'auto',
  writingMode: 'horizontal-tb',
  zIndex: 'auto',
};

/** Border groups — if width is 0, skip style and color */
export const BORDER_GROUPS = [
  { style: 'borderTopStyle', width: 'borderTopWidth', color: 'borderTopColor' },
  { style: 'borderRightStyle', width: 'borderRightWidth', color: 'borderRightColor' },
  { style: 'borderBottomStyle', width: 'borderBottomWidth', color: 'borderBottomColor' },
  { style: 'borderLeftStyle', width: 'borderLeftWidth', color: 'borderLeftColor' },
];

/** Semantic HTML attributes worth preserving */
export const PRESERVED_ATTRS = new Set([
  'alt', 'checked', 'currentSrc', 'disabled', 'for', 'href', 'id',
  'multiple', 'placeholder', 'poster', 'readonly', 'rel', 'required',
  'role', 'selected', 'target', 'title', 'type', 'value',
  'data-figma-id', 'data-component',
]);

/** Input types that have text content */
export const TEXT_INPUT_TYPES = new Set([
  'text', 'search', 'tel', 'url', 'email', 'password', 'number',
]);
